# 开发环境的公共配置
spring:
   profiles:
      # 引用 application-mysql.yml 文件,可选项为  h2/mysql
      include: mysql

   datasource:
      url: jdbc:mysql://127.0.0.1:3306/db_mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root